"""
Feature mapping utility for cross-site harmonization.
- Glomerular (59 features)
- Tubular (48 features)
- Vascular/Arterial (58 features)

Total: 165 matched features
"""

def get_feature_mapping():

    
    feature_mapping = {
        # GLOMERULAR FEATURES (U _glom → C _reviewed_MF01)
        'Sum Distance Transform By Object Area Nuclei_glom': 'Sum_Distance_TF_By_Object_Area_Nuclei_reviewed_MF01',
        'Sum Distance Transform By Nuclei Area_glom': 'Sum_Distance_TF_By_Nuclei_Area_reviewed_MF01',
        'Sum Distance Transform Nuclei_glom': 'Sum_Distance_TF_Nuclei_reviewed_MF01',
        'Mean Distance Transform By Object Area Nuclei_glom': 'Mean_Distance_TF_By_Object_Area_Nuclei_reviewed_MF01',
        'Mean Distance Transform By Nuclei Area_glom': 'Mean_Distance_TF_By_Nuclei_Area_reviewed_MF01',
        'Mean Distance Transform Nuclei_glom': 'Mean_Distance_TF_Nuclei_reviewed_MF01',
        'Max Distance Transform By Object Area Nuclei_glom': 'Max_Distance_TF_By_Object_Area_Nuclei_reviewed_MF01',
        'Max Distance Transform By Nuclei Area_glom': 'Max_Distance_TF_By_Nuclei_Area_reviewed_MF01',
        'Max Distance Transform Nuclei_glom': 'Max_Distance_TF_Nuclei_reviewed_MF01',
        'Sum Distance Transform By Object Area Eosinophilic_glom': 'Sum_Distance_TF_By_Object_Area_Eosinophilic_reviewed_MF01',
        'Sum Distance Transform By Eosinophilic Area_glom': 'Sum_Distance_TF_By_Eosinophilic_Area_reviewed_MF01',
        'Sum Distance Transform Eosinophilic_glom': 'Sum_Distance_TF_Eosinophilic_reviewed_MF01',
        'Mean Distance Transform By Object Area Eosinophilic_glom': 'Mean_Distance_TF_By_Object_Area_Eosinophilic_reviewed_MF01',
        'Mean Distance Transform By Eosinophilic Area_glom': 'Mean_Distance_TF_By_Eosinophilic_Area_reviewed_MF01',
        'Mean Distance Transform Eosinophilic_glom': 'Mean_Distance_TF_Eosinophilic_reviewed_MF01',
        'Max Distance Transform By Object Area Eosinophilic_glom': 'Max_Distance_TF_By_Object_Area_Eosinophilic_reviewed_MF01',
        'Max Distance Transform By Eosinophilic Area_glom': 'Max_Distance_TF_By_Eosinophilic_Area_reviewed_MF01',
        'Max Distance Transform Eosinophilic_glom': 'Max_Distance_TF_Eosinophilic_reviewed_MF01',
        'Sum Distance Transform By Object Area Luminal Space_glom': 'Sum_Distance_TF_By_Object_Area_Luminal_Space_reviewed_MF01',
        'Sum Distance Transform By Luminal Space Area_glom': 'Sum_Distance_TF_By_Luminal_Space_Area_reviewed_MF01',
        'Sum Distance Transform Luminal Space_glom': 'Sum_Distance_TF_Luminal_Space_reviewed_MF01',
        'Mean Distance Transform By Object Area Luminal Space_glom': 'Mean_Distance_TF_By_Object_Area_Luminal_Space_reviewed_MF01',
        'Mean Distance Transform By Luminal Space Area_glom': 'Mean_Distance_TF_By_Luminal_Space_Area_reviewed_MF01',
        'Mean Distance Transform Luminal Space_glom': 'Mean_Distance_TF_Luminal_Space_reviewed_MF01',
        'Max Distance Transform By Object Area Luminal Space_glom': 'Max_Distance_TF_By_Object_Area_Luminal_Space_reviewed_MF01',
        'Max Distance Transform By Luminal Space Area_glom': 'Max_Distance_TF_By_Luminal_Space_Area_reviewed_MF01',
        'Max Distance Transform Luminal Space_glom': 'Max_Distance_TF_Luminal_Space_reviewed_MF01',
        'Contrast Nuclei_glom': 'Contrast_Nuclei_reviewed_MF01',
        'Homogeneity Nuclei_glom': 'Homogeneity_Nuclei_reviewed_MF01',
        'Correlation Nuclei_glom': 'Correlation_Nuclei_reviewed_MF01',
        'Energy Nuclei_glom': 'Energy_Nuclei_reviewed_MF01',
        'Contrast Eosinophilic_glom': 'Contrast_Eosinophilic_reviewed_MF01',
        'Homogeneity Eosinophilic_glom': 'Homogeneity_Eosinophilic_reviewed_MF01',
        'Correlation Eosinophilic_glom': 'Correlation_Eosinophilic_reviewed_MF01',
        'Energy Eosinophilic_glom': 'Energy_Eosinophilic_reviewed_MF01',
        'Contrast Luminal Space_glom': 'Contrast_Luminal_Space_reviewed_MF01',
        'Homogeneity Luminal Space_glom': 'Homogeneity_Luminal_Space_reviewed_MF01',
        'Correlation Luminal Space_glom': 'Correlation_Luminal_Space_reviewed_MF01',
        'Energy Luminal Space_glom': 'Energy_Luminal_Space_reviewed_MF01',
        'Nuclei Area By Object Area_glom': 'Nuclei_Area_By_Object_Area_reviewed_MF01',
        'Nuclei Area_glom': 'Nuclei_Area_reviewed_MF01',
        'Eosinophilic Area By Object Area_glom': 'Eosinophilic_Area_By_Object_Area_reviewed_MF01',
        'Eosinophilic Area_glom': 'Eosinophilic_Area_reviewed_MF01',
        'Luminal Space Area By Object Area_glom': 'Luminal_Space_Area_By_Object_Area_reviewed_MF01',
        'Luminal Space Area_glom': 'Luminal_Space_Area_reviewed_MF01',
        'Nuclei Number_glom': 'Nuclei_Number_reviewed_MF01',
        'Mean Aspect Ratio Nuclei_glom': 'Mean_Aspect_Ratio_Nuclei_reviewed_MF01',
        'Standard Deviation Aspect Ratio Nuclei_glom': 'Standard_Deviation_Aspect_Ratio_Nuclei_reviewed_MF01',
        'Mean Nuclear Area_glom': 'Mean_Nuclear_Area_reviewed_MF01',
        'Total Object Area_glom': 'Total_Object_Area_reviewed_MF01',
        'Total Object Perimeter_glom': 'Total_Object_Perimeter_reviewed_MF01',
        'Total Object Aspect Ratio_glom': 'Total_Object_Aspect_Ratio_reviewed_MF01',
        'Major Axis Length_glom': 'Major_Axis_Length_reviewed_MF01',
        'Minor Axis Length_glom': 'Minor_Axis_Length_reviewed_MF01',
        'Area (pixel^2)_glom': 'Area_pixel_2_Extended_Clinical_reviewed_MF01',
        'Radius (pixel)_glom': 'Radius_pixel_Extended_Clinical_reviewed_MF01',
        'Area_glom': 'Area_reviewed_MF01',
        'Mesangial Area_glom': 'Glomerular_Mesangial_Area_Reviewed_MF01',
        'Mesangial Fraction_glom': 'Glomerular_Mesangial_Fraction_Reviewed_MF01',
        
        # TUBULAR FEATURES (U _tubule → C _TF_CT_rev)
        'Sum Distance Transform By Object Area Nuclei_tubule': 'Sum_Distance_Transform_By_Object_Area_Nuclei_TF_CT_rev',
        'Sum Distance Transform By Nuclei Area_tubule': 'Sum_Distance_Transform_By_Nuclei_Area_TF_CT_rev',
        'Sum Distance Transform Nuclei_tubule': 'Sum_Distance_Transform_Nuclei_TF_CT_rev',
        'Mean Distance Transform By Object Area Nuclei_tubule': 'Mean_Distance_Transform_By_Object_Area_Nuclei_TF_CT_rev',
        'Mean Distance Transform By Nuclei Area_tubule': 'Mean_Distance_Transform_By_Nuclei_Area_TF_CT_rev',
        'Mean Distance Transform Nuclei_tubule': 'Mean_Distance_Transform_Nuclei_TF_CT_rev',
        'Max Distance Transform By Object Area Nuclei_tubule': 'Max_Distance_Transform_By_Object_Area_Nuclei_TF_CT_rev',
        'Max Distance Transform By Nuclei Area_tubule': 'Max_Distance_Transform_By_Nuclei_Area_TF_CT_rev',
        'Max Distance Transform Nuclei_tubule': 'Max_Distance_Transform_Nuclei_TF_CT_rev',
        'Sum Distance Transform By Object Area Eosinophilic_tubule': 'Sum_Distance_Transform_By_Object_Area_Eosinophilic_TF_CT_rev',
        'Sum Distance Transform By Eosinophilic Area_tubule': 'Sum_Distance_Transform_By_Eosinophilic_Area_TF_CT_rev',
        'Sum Distance Transform Eosinophilic_tubule': 'Sum_Distance_Transform_Eosinophilic_TF_CT_rev',
        'Mean Distance Transform By Object Area Eosinophilic_tubule': 'Mean_Distance_Transform_By_Object_Area_Eosinophilic_TF_CT_rev',
        'Mean Distance Transform By Eosinophilic Area_tubule': 'Mean_Distance_Transform_By_Eosinophilic_Area_TF_CT_rev',
        'Mean Distance Transform Eosinophilic_tubule': 'Mean_Distance_Transform_Eosinophilic_TF_CT_rev',
        'Max Distance Transform By Object Area Eosinophilic_tubule': 'Max_Distance_Transform_By_Object_Area_Eosinophilic_TF_CT_rev',
        'Max Distance Transform By Eosinophilic Area_tubule': 'Max_Distance_Transform_By_Eosinophilic_Area_TF_CT_rev',
        'Max Distance Transform Eosinophilic_tubule': 'Max_Distance_Transform_Eosinophilic_TF_CT_rev',
        'Sum Distance Transform By Object Area Luminal Space_tubule': 'Sum_Distance_Transform_By_Object_Area_Luminal_Space_TF_CT_rev',
        'Sum Distance Transform By Luminal Space Area_tubule': 'Sum_Distance_Transform_By_Luminal_Space_Area_TF_CT_rev',
        'Sum Distance Transform Luminal Space_tubule': 'Sum_Distance_Transform_Luminal_Space_TF_CT_rev',
        'Mean Distance Transform By Object Area Luminal Space_tubule': 'Mean_Distance_Transform_By_Object_Area_Luminal_Space_TF_CT_rev',
        'Mean Distance Transform By Luminal Space Area_tubule': 'Mean_Distance_Transform_By_Luminal_Space_Area_TF_CT_rev',
        'Mean Distance Transform Luminal Space_tubule': 'Mean_Distance_Transform_Luminal_Space_TF_CT_rev',
        'Max Distance Transform By Object Area Luminal Space_tubule': 'Max_Distance_Transform_By_Object_Area_Luminal_Space_TF_CT_rev',
        'Max Distance Transform By Luminal Space Area_tubule': 'Max_Distance_Transform_By_Luminal_Space_Area_TF_CT_rev',
        'Max Distance Transform Luminal Space_tubule': 'Max_Distance_Transform_Luminal_Space_TF_CT_rev',
        'Contrast Nuclei_tubule': 'Contrast_Nuclei_TF_CT_rev',
        'Homogeneity Nuclei_tubule': 'Homogeneity_Nuclei_TF_CT_rev',
        'Correlation Nuclei_tubule': 'Correlation_Nuclei_TF_CT_rev',
        'Energy Nuclei_tubule': 'Energy_Nuclei_TF_CT_rev',
        'Contrast Eosinophilic_tubule': 'Contrast_Eosinophilic_TF_CT_rev',
        'Homogeneity Eosinophilic_tubule': 'Homogeneity_Eosinophilic_TF_CT_rev',
        'Correlation Eosinophilic_tubule': 'Correlation_Eosinophilic_TF_CT_rev',
        'Energy Eosinophilic_tubule': 'Energy_Eosinophilic_TF_CT_rev',
        'Contrast Luminal Space_tubule': 'Contrast_Luminal_Space_TF_CT_rev',
        'Homogeneity Luminal Space_tubule': 'Homogeneity_Luminal_Space_TF_CT_rev',
        'Correlation Luminal Space_tubule': 'Correlation_Luminal_Space_TF_CT_rev',
        'Energy Luminal Space_tubule': 'Energy_Luminal_Space_TF_CT_rev',
        'Nuclei Area By Object Area_tubule': 'Nuclei_Area_By_Object_Area_TF_CT_rev',
        'Nuclei Area_tubule': 'Nuclei_Area_TF_CT_rev',
        'Eosinophilic Area By Object Area_tubule': 'Eosinophilic_Area_By_Object_Area_TF_CT_rev',
        'Eosinophilic Area_tubule': 'Eosinophilic_Area_TF_CT_rev',
        'Luminal Space Area By Object Area_tubule': 'Luminal_Space_Area_By_Object_Area_TF_CT_rev',
        'Luminal Space Area_tubule': 'Luminal_Space_Area_TF_CT_rev',
        'Nuclei Number_tubule': 'Nuclei_Number_TF_CT_rev',
        'Mean Aspect Ratio Nuclei_tubule': 'Mean_Aspect_Ratio_Nuclei_TF_CT_rev',
        'Standard Deviation Aspect Ratio Nuclei_tubule': 'Standard_Deviation_Aspect_Ratio_Nuclei_TF_CT_rev',
        'Mean Nuclear Area_tubule': 'Mean_Nuclear_Area_TF_CT_rev',
        'Total Object Area_tubule': 'Total_Object_Area_TF_CT_rev',
        'Total Object Perimeter_tubule': 'Total_Object_Perimeter_TF_CT_rev',
        'Total Object Aspect Ratio_tubule': 'Total_Object_Aspect_Ratio_TF_CT_rev',
        'Major Axis Length_tubule': 'Major_Axis_Length_TF_CT_rev',
        'Minor Axis Length_tubule': 'Minor_Axis_Length_TF_CT_rev',
        'Area (pixel^2)_tubule': 'Area_pixel2_TF_CT_rev',
        'Radius (pixel)_tubule': 'Radius_pixel_TF_CT_rev',
        'Average TBM Thickness_tubule': 'TUBULAR_Average_TBM_Thickness_TF_CT_Rev',
        'Average Cell Thickness_tubule': 'TUBULAR_Average_Cell_Thickness_TF_CT_Rev',
        'Luminal Fraction_tubule': 'TUBULAR_Luminal_Fraction_TF_Rev',
        
        # VASCULAR/ARTERIAL FEATURES (U _artery → C _V_Mean_rev)
        'Sum Distance Transform By Object Area Nuclei_artery': 'Sum_Distance_Transform_By_Object_Area_Nuclei_V_Mean_rev',
        'Sum Distance Transform By Nuclei Area_artery': 'Sum_Distance_Transform_By_Nuclei_Area_V_Mean_rev',
        'Sum Distance Transform Nuclei_artery': 'Sum_Distance_Transform_Nuclei_V_Mean_rev',
        'Mean Distance Transform By Object Area Nuclei_artery': 'Mean_Distance_Transform_By_Object_Area_Nuclei_V_Mean_rev',
        'Mean Distance Transform By Nuclei Area_artery': 'Mean_Distance_Transform_By_Nuclei_Area_V_Mean_rev',
        'Mean Distance Transform Nuclei_artery': 'Mean_Distance_Transform_Nuclei_V_Mean_rev',
        'Max Distance Transform By Object Area Nuclei_artery': 'Max_Distance_Transform_By_Object_Area_Nuclei_V_Mean_rev',
        'Max Distance Transform By Nuclei Area_artery': 'Max_Distance_Transform_By_Nuclei_Area_V_Mean_rev',
        'Max Distance Transform Nuclei_artery': 'Max_Distance_Transform_Nuclei_V_Mean_rev',
        'Sum Distance Transform By Object Area Eosinophilic_artery': 'Sum_Distance_Transform_By_Object_Area_Eosinophilic_V_Mean_rev',
        'Sum Distance Transform By Eosinophilic Area_artery': 'Sum_Distance_Transform_By_Eosinophilic_Area_V_Mean_rev',
        'Sum Distance Transform Eosinophilic_artery': 'Sum_Distance_Transform_Eosinophilic_V_Mean_rev',
        'Mean Distance Transform By Object Area Eosinophilic_artery': 'Mean_Distance_Transform_By_Object_Area_Eosinophilic_V_Mean_rev',
        'Mean Distance Transform By Eosinophilic Area_artery': 'Mean_Distance_Transform_By_Eosinophilic_Area_V_Mean_rev',
        'Mean Distance Transform Eosinophilic_artery': 'Mean_Distance_Transform_Eosinophilic_V_Mean_rev',
        'Max Distance Transform By Object Area Eosinophilic_artery': 'Max_Distance_Transform_By_Object_Area_Eosinophilic_V_Mean_rev',
        'Max Distance Transform By Eosinophilic Area_artery': 'Max_Distance_Transform_By_Eosinophilic_Area_V_Mean_rev',
        'Max Distance Transform Eosinophilic_artery': 'Max_Distance_Transform_Eosinophilic_V_Mean_rev',
        'Sum Distance Transform By Object Area Luminal Space_artery': 'Sum_Distance_Transform_By_Object_Area_Luminal_Space_V_Mean_rev',
        'Sum Distance Transform By Luminal Space Area_artery': 'Sum_Distance_Transform_By_Luminal_Space_Area_V_Mean_rev',
        'Sum Distance Transform Luminal Space_artery': 'Sum_Distance_Transform_Luminal_Space_V_Mean_rev',
        'Mean Distance Transform By Object Area Luminal Space_artery': 'Mean_Distance_Transform_By_Object_Area_Luminal_Space_V_Mean_rev',
        'Mean Distance Transform By Luminal Space Area_artery': 'Mean_Distance_Transform_By_Luminal_Space_Area_V_Mean_rev',
        'Mean Distance Transform Luminal Space_artery': 'Mean_Distance_Transform_Luminal_Space_V_Mean_rev',
        'Max Distance Transform By Object Area Luminal Space_artery': 'Max_Distance_Transform_By_Object_Area_Luminal_Space_V_Mean_rev',
        'Max Distance Transform By Luminal Space Area_artery': 'Max_Distance_Transform_By_Luminal_Space_Area_V_Mean_rev',
        'Max Distance Transform Luminal Space_artery': 'Max_Distance_Transform_Luminal_Space_V_Mean_rev',
        'Contrast Nuclei_artery': 'Contrast_Nuclei_V_Mean_rev',
        'Homogeneity Nuclei_artery': 'Homogeneity_Nuclei_V_Mean_rev',
        'Correlation Nuclei_artery': 'Correlation_Nuclei_V_Mean_rev',
        'Energy Nuclei_artery': 'Energy_Nuclei_V_Mean_rev',
        'Contrast Eosinophilic_artery': 'Contrast_Eosinophilic_V_Mean_rev',
        'Homogeneity Eosinophilic_artery': 'Homogeneity_Eosinophilic_V_Mean_rev',
        'Correlation Eosinophilic_artery': 'Correlation_Eosinophilic_V_Mean_rev',
        'Energy Eosinophilic_artery': 'Energy_Eosinophilic_V_Mean_rev',
        
        # Texture Features - Luminal Space (4 features)
        'Contrast Luminal Space_artery': 'Contrast_Luminal_Space_V_Mean_rev',
        'Homogeneity Luminal Space_artery': 'Homogeneity_Luminal_Space_V_Mean_rev',
        'Correlation Luminal Space_artery': 'Correlation_Luminal_Space_V_Mean_rev',
        'Energy Luminal Space_artery': 'Energy_Luminal_Space_V_Mean_rev',
        
        # Area Features (6 features)
        'Nuclei Area By Object Area_artery': 'Nuclei_Area_By_Object_Area_V_Mean_rev',
        'Nuclei Area_artery': 'Nuclei_Area_V_Mean_rev',
        'Eosinophilic Area By Object Area_artery': 'Eosinophilic_Area_By_Object_Area_V_Mean_rev',
        'Eosinophilic Area_artery': 'Eosinophilic_Area_V_Mean_rev',
        'Luminal Space Area By Object Area_artery': 'Luminal_Space_Area_By_Object_Area_V_Mean_rev',
        'Luminal Space Area_artery': 'Luminal_Space_Area_V_Mean_rev',
        
        # Nuclear Features (4 features)
        'Nuclei Number_artery': 'Nuclei_Number_V_Mean_rev',
        'Mean Aspect Ratio Nuclei_artery': 'Mean_Aspect_Ratio_Nuclei_V_Mean_rev',
        'Standard Deviation Aspect Ratio Nuclei_artery': 'Standard_Deviation_Aspect_Ratio_Nuclei_V_Mean_rev',
        'Mean Nuclear Area_artery': 'Mean_Nuclear_Area_V_Mean_rev',
        
        # Object Morphology Features (5 features)
        'Total Object Area_artery': 'Total_Object_Area_V_Mean_rev',
        'Total Object Perimeter_artery': 'Total_Object_Perimeter_V_Mean_rev',
        'Total Object Aspect Ratio_artery': 'Total_Object_Aspect_Ratio_V_Mean_rev',
        'Major Axis Length_artery': 'Major_Axis_Length_V_Mean_rev',
        'Minor Axis Length_artery': 'Minor_Axis_Length_V_Mean_rev',
        
        # Pixel-based Features (2 features)
        'Area (pixel^2)_artery': 'Area_pixel2_V_Mean_rev',
        'Radius (pixel)_artery': 'Radius_pixel_V_Mean_rev',
        
        # Vascular-specific Features (2 features)
        'Luminal ratio_artery': 'VASCULAR_Luminal_ratio_Mean_Rev',
        'Arterial Area_artery': 'VASCULAR_Arterial_Area_Mean_Rev',
    }
    
    return feature_mapping
